name: gh-release-preview

on:
  pull_request:
    types: 
      - opened
      - synchronize
    branches:
      - main
    paths:
      - "**/RELEASE"

jobs:
  gh-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pipe-cd/actions-gh-release@v2.6.0
        with:
          release_file: "**/RELEASE"
          token: ${{ secrets.GITHUB_TOKEN }}

  # preview:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: pipe-cd/actions-gh-release@v2.6.0
  #       with:
  #         release_file: "**/RELEASE"
  #         token: ${{ secrets.GITHUB_TOKEN }}
